# Generated by Django 4.2 on 2026-05-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audithistory',
            name='full_report',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='audithistory',
            name='grade',
            field=models.CharField(default='F', max_length=10),
        ),
        migrations.AlterField(
            model_name='audithistory',
            name='security_score',
            field=models.IntegerField(default=0),
        ),
    ]
